### ISSUE TITLE
彻底清除公众号文章顽疾广告，就不发pr了

### ISSUE THREAD

**Issue by doKill** [ddgksf2013/Rewrite#8]
加入两条规则
```
^https?:\/\/mp\.weixin\.qq\.com\/mp\/(advertisement_report|cps_product_info|wapcommreport|jsreport|jsmonitor|getappmsgext) url reject
^https?:\/\/wxa\.wxs\.qq\.com\/tmpl\/kf\/base_tmpl\.html url reject
```

hostname 增加 wsa.wsx.qq.com

**Comment by doKill** [comment]
看来复制过来的反斜杠被转义了

**Comment by doKill** [comment]
`
^https?:\/\/mp\.weixin\.qq\.com\/mp\/(advertisement_report|cps_product_info|wapcommreport|jsreport|jsmonitor|getappmsgext) url reject
^https?:\/\/wxa\.wxs\.qq\.com\/tmpl\/kf\/base_tmpl\.html url reject
`

**Comment by ddgksf2013** [comment]
COMPLETE
